# Window
window_padding_width 4
background_opacity 1.0

# Font
font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font Bold
italic_font      FiraCode Nerd Font Italic
bold_italic_font FiraCode Nerd Font Bold Italic
font_size 16.0

# Colors - Primary
background #222222
foreground #eeeeee

# Colors - Normal
color0  #1c1c1c
color1  #ff5f5f
color2  #5fff87
color3  #ffd75f
color4  #5fafff
color5  #d75fff
color6  #5fd7ff
color7  #d0d0d0

# Colors - Bright
color8  #444444
color9  #ff8787
color10 #87ffaf
color11 #ffdf87
color12 #87afff
color13 #e7a7ff
color14 #87dfff
color15 #ffffff
