Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"

    Option "Tapping" "on"
    Option "NaturalScrolling" "on"
    Option "DisableWhileTyping" "off"
    Option "MiddleEmulation" "on"
EndSection

# /etc/X11/xorg.conf.d/30-touchpad.conf

